// 2024 YKS sınavında çıkan dersler ve konuları - TYT ve AYT olarak ayrılmış
const yksData = {
  TYT: {
    "Türkçe": {
      color: "#4285f4",
      topics: [
        "Sözcükte Anlam",
        "Söz Yorumu",
        "Deyim ve Atasözü",
        "Cümlede Anlam",
        "Paragraf",
        "Paragrafta Anlatım Teknikleri",
        "Paragrafta Düşünceyi Geliştirme Yolları",
        "Paragrafta Yapı",
        "Paragrafta Konu-Ana Düşünce",
        "Paragrafta Yardımcı Düşünce",
        "Ses Bilgisi",
        "Yazım Kuralları",
        "Noktalama İşaretleri",
        "Sözcükte Yapı/Ekler",
        "Sözcük Türleri",
        "İsimler",
        "Zamirler",
        "Sıfatlar",
        "Zarflar",
        "Edat – Bağlaç – Ünlem",
        "Fiiller",
        "Fiilde Anlam (Kip-Kişi-Yapı)",
        "Ek Fiil",
        "Fiilimsi",
        "Fiilde Çatı",
        "Sözcük Grupları",
        "Cümlenin Ögeleri",
        "Cümle Türleri",
        "Anlatım Bozukluğu"
      ]
    },
    "Tarih": {
      color: "#9c27b0",
      topics: [
        "Tarih ve Zaman",
        "İnsanlığın İlk Dönemleri",
        "Ortaçağ'da Dünya",
        "İlk ve Orta Çağlarda Türk Dünyası",
        "İslam Medeniyetinin Doğuşu",
        "İlk Türk İslam Devletleri",
        "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
        "Beylikten Devlete Osmanlı Siyaseti(1300-1453)",
        "Dünya Gücü Osmanlı Devleti (1453-1600)",
        "Yeni Çağ Avrupa Tarihi",
        "Yakın Çağ Avrupa Tarihi",
        "Osmanlı Devletinde Arayış Yılları",
        "18. Yüzyılda Değişim ve Diplomasi",
        "En Uzun Yüzyıl",
        "Osmanlı Kültür ve Medeniyeti",
        "20. Yüzyılda Osmanlı Devleti",
        "I. Dünya Savaşı",
        "Mondros Ateşkesi, İşgaller ve Cemiyetler",
        "Kurtuluş Savaşına Hazırlık Dönemi",
        "I. TBMM Dönemi",
        "Kurtuluş Savaşı ve Antlaşmalar",
        "II. TBMM Dönemi ve Çok Partili Hayata Geçiş",
        "Türk İnkılabı",
        "Atatürk İlkeleri",
        "Atatürk Dönemi Türk Dış Politikası"
      ]
    },
    "Coğrafya": {
      color: "#795548",
      topics: [
        "Doğa ve İnsan",
        "Dünya'nın Şekli ve Hareketleri",
        "Coğrafi Konum",
        "Harita Bilgisi",
        "Atmosfer ve Sıcaklık",
        "İklimler",
        "Basınç ve Rüzgarlar",
        "Nem, Yağış ve Buharlaşma",
        "İç Kuvvetler / Dış Kuvvetler",
        "Su – Toprak ve Bitkiler",
        "Nüfus",
        "Göç",
        "Yerleşme",
        "Türkiye'nin Yer Şekilleri",
        "Ekonomik Faaliyetler",
        "Bölgeler",
        "Uluslararası Ulaşım Hatları",
        "Çevre ve Toplum",
        "Doğal Afetler"
      ]
    },
    "Felsefe": {
      color: "#607d8b",
      topics: [
        "Felsefenin Konusu",
        "Bilgi Felsefesi",
        "Varlık Felsefesi",
        "Din, Kültür ve Medniyet",
        "Ahlak Felsefesi",
        "Sanat Felsefesi",
        "Din Felsefesi",
        "Siyaset Felsefesi",
        "Bilim Felsefesi"
      ]
    },
    "Din Kültürü": {
      color: "#00bcd4",
      topics: [
        "İnanç",
        "İbadet",
        "Ahlak ve Değerler",
        "Din, Kültür ve Medniyet",
        "Hz. Muhammed (S.A.V.)",
        "Vahiy ve Akıl",
        "Dünya ve Ahiret",
        "Kur'an'a göre Hz. Muhammed (S.A.V.)",
        "İnançla İlgili Meseleler",
        "Yahudilik ve Hristiyanlık",
        "İslam ve Bilim",
        "Anadolu da İslam",
        "İslam Düşüncesinde Tasavvufi Yorumlar",
        "Güncel Dini Meseler",
        "Hint ve Çin Dinleri"
      ]
    },
    "Temel Matematik": {
      color: "#34a853",
      topics: [
        "Temel Kavramlar",
        "Sayı Basamakları",
        "Bölme ve Bölünebilme",
        "EBOB – EKOK",
        "Rasyonel Sayılar",
        "Basit Eşitsizlikler",
        "Mutlak Değer",
        "Üslü Sayılar",
        "Köklü Sayılar",
        "Çarpanlara Ayırma",
        "Oran Orantı",
        "Denklem Çözme",
        "Problemler",
        "Sayı Problemleri",
        "Kesir Problemleri",
        "Yaş Problemleri",
        "Hareket Hız Problemleri",
        "İşçi Emek Problemleri",
        "Yüzde Problemleri",
        "Kar Zarar Problemleri",
        "Karışım Problemleri",
        "Grafik Problemleri",
        "Rutin Olmayan Problemleri",
        "Kümeler – Kartezyen Çarpım",
        "Mantık",
        "Fonskiyonlar",
        "Polinomlar",
        "2.Dereceden Denklemler",
        "Permütasyon ve Kombinasyon",
        "Olasılık",
        "Veri – İstatistik"
      ]
    },
    "Fizik": {
      color: "#ea4335",
      topics: [
        "Fizik Bilimine Giriş",
        "Madde ve Özellikleri",
        "Sıvıların Kaldırma Kuvveti",
        "Basınç",
        "Isı, Sıcaklık ve Genleşme",
        "Hareket ve Kuvvet",
        "Dinamik",
        "İş, Güç ve Enerji",
        "Elektrik",
        "Manyetizma",
        "Dalgalar",
        "Optik"
      ]
    },
    "Kimya": {
      color: "#fbbc05",
      topics: [
        "Kimya Bilimi",
        "Atom ve Yapısı",
        "Periyodik Sistem",
        "Kimyasal Türler Arası Etkileşimler",
        "Maddenin Halleri",
        "Kimyanın Temel Kanunları",
        "Asitler, Bazlar ve Tuzlar",
        "Kimyasal Hesaplamalar",
        "Karışımlar",
        "Endüstride ve Canlılarda Enerji",
        "Kimya Her Yerde"
      ]
    },
    "Biyoloji": {
      color: "#0f9d58",
      topics: [
        "Canlıların Ortak Özellikleri",
        "Canlıların Temel Bileşenleri",
        "Hücre ve Organeller – Madde Geçişleri",
        "Canlıların Sınıflandırılması",
        "Hücrede Bölünme – Üreme",
        "Kalıtım",
        "Bitki Biyolojisi",
        "Ekosistem"
      ]
    }
  },
  AYT: {
    "Matematik": {
      color: "#34a853",
      topics: [
        "Fonksiyonlar",
        "Polinomlar",
        "Dereceden Denklemler",
        "Karmaşık Sayılar",
        "Permütasyon",
        "Kombinasyon",
        "Olasılık",
        "Binom",
        "Trigonometri",
        "Logaritma",
        "Diziler",
        "Limit",
        "Süreklilik",
        "Türev",
        "Türev Uygulamaları",
        "İntegral",
        "İntegral Uygulamaları",
        "Analitik Geometri (Doğru, Parabol vs.)"
      ]
    },
    "Edebiyat": {
      color: "#4285f4",
      topics: [
        "Anlam Bilgisi",
        "Dil Bilgisi",
        "Güzel Sanatlar ve Edebiyat",
        "Metinlerin Sınıflandırılması",
        "Şiir Bilgisi",
        "Edebi Sanatlar",
        "Türk Edebiyatı Dönemleri",
        "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi",
        "Halk Edebiyatı",
        "Divan Edebiyatı",
        "Tanzimat Edebiyatı",
        "Servet-i Fünun Edebiyatı",
        "Fecr-i Ati Edebiyatı",
        "Milli Edebiyat",
        "Cumhuriyet Dönemi Edebiyatı",
        "Edebiyat Akımları",
        "Dünya Edebiyatı"
      ]
    },
    "Fizik": {
      color: "#ea4335",
      topics: [
        "Vektörler",
        "Kuvvet, Tork ve Denge",
        "Kütle Merkezi",
        "Basit Makineler",
        "Hareket",
        "Newton'un Hareket Yasaları",
        "İş, Güç ve Enerji II",
        "Atışlar",
        "İtme ve Momentum",
        "Elektrik Alan ve Potansiyel",
        "Paralel Levhalar ve Sığa",
        "Manyetik Alan ve Manyetik Kuvvet",
        "İndüksiyon, Alternatif Akım ve Transformatörler",
        "Çembersel Hareket",
        "Dönme, Yuvarlanma ve Açısal Momentum",
        "Kütle Çekim ve Kepler Yasaları",
        "Basit Harmonik Hareket",
        "Dalga Mekaniği ve Elektromanyetik Dalgalar",
        "Atom Modelleri",
        "Büyük Patlama ve Parçacık Fiziği",
        "Radyoaktivite",
        "Özel Görelilik",
        "Kara Cisim Işıması",
        "Fotoelektrik Olay ve Compton Olayı",
        "Modern Fiziğin Teknolojideki Uygulamaları"
      ]
    },
    "Biyoloji": {
      color: "#0f9d58",
      topics: [
        "Sinir Sistemi",
        "Endokrin Sistem ve Hormonlar",
        "Duyu Organları",
        "Destek ve Hareket Sistemi",
        "Sindirim Sistemi",
        "Dolaşım ve Bağışıklık Sistemi",
        "Solunum Sistemi",
        "Üriner Sistem (Boşaltım Sistemi)",
        "Üreme Sistemi ve Embriyonik Gelişim",
        "Komünite Ekolojisi",
        "Popülasyon Ekolojisi",
        "Genden Proteine",
        "Nükleik Asitler",
        "Genetik Şifre ve Protein Sentezi",
        "Canlılarda Enerji Dönüşümleri",
        "Canlılık ve Enerji",
        "Fotosentez",
        "Kemosentez",
        "Hücresel Solunum",
        "Bitki Biyolojisi",
        "Canlılar ve Çevre"
      ]
    },
    "Kimya": {
      color: "#fbbc05",
      topics: [
        "Kimya Bilimi",
        "Atom ve Periyodik Sistem",
        "Kimyasal Türler Arası Etkileşimler",
        "Kimyasal Hesaplamalar",
        "Kimyanın Temel Kanunları",
        "Asit, Baz ve Tuz",
        "Maddenin Halleri",
        "Karışımlar",
        "Doğa ve Kimya",
        "Kimya Her Yerde",
        "Modern Atom Teorisi",
        "Gazlar",
        "Sıvı Çözeltiler",
        "Kimyasal Tepkimelerde Enerji",
        "Kimyasal Tepkimelerde Hız",
        "Kimyasal Tepkimelerde Denge",
        "Asit-Baz Dengesi",
        "Çözünürlük Dengesi",
        "Kimya ve Elektrik",
        "Organik Kimyaya Giriş",
        "Organik Kimya",
        "Enerji Kaynakları ve Bilimsel Gelişmeler"
      ]
    },
    "Tarih": {
      color: "#9c27b0",
      topics: [
        "Tarih ve Zaman",
        "İnsanlığın İlk Dönemleri",
        "Orta Çağ'da Dünya",
        "İlk ve Orta Çağlarda Türk Dünyası",
        "İslam Medeniyetinin Doğuşu",
        "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
        "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
        "Beylikten Devlete Osmanlı Siyaseti",
        "Devletleşme Sürecinde Savaşçılar ve Askerler",
        "Beylikten Devlete Osmanlı Medeniyeti",
        "Dünya Gücü Osmanlı",
        "Sultan ve Osmanlı Merkez Teşkilatı",
        "Klasik Çağda Osmanlı Toplum Düzeni",
        "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
        "Değişim Çağında Avrupa ve Osmanlı",
        "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
        "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
        "Sermaye ve Emek",
        "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
        "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
        "Milli Mücadele",
        "Atatürkçülük ve Türk İnkılabı",
        "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
        "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
        "II. Dünya Savaşı Sonrasında Türkiye ve Dünya",
        "Toplumsal Devrim Çağında Dünya ve Türkiye",
        "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya"
      ]
    },
    "Coğrafya": {
      color: "#795548",
      topics: [
        "Ekosistem",
        "Biyoçeşitlilik",
        "Biyomlar",
        "Ekosistemin Unsurları",
        "Enerji Akışı ve Madde Döngüsü",
        "Ekstrem Doğa Olayları",
        "Küresel İklim Değişimi",
        "Nüfus Politikaları",
        "Türkiye'de Nüfus ve Yerleşme",
        "Ekonomik Faaliyetler ve Doğal Kaynaklar",
        "Göç ve Şehirleşme",
        "Türkiye Ekonomisi",
        "Türkiye'nin Ekonomi Politikaları",
        "Türkiye Ekonomisinin Sektörel Dağılımı",
        "Türkiye'de Tarım",
        "Türkiye'de Hayvancılık",
        "Türkiye'de Madenler ve Enerji Kaynakları",
        "Türkiye'de Sanayi",
        "Türkiye'de Ulaşım",
        "Türkiye'de Ticaret ve Turizm",
        "Geçmişten Geleceğe Şehir ve Ekonomi",
        "Türkiye'nin İşlevsel Bölgeleri ve Kalkınma Projeleri",
        "Hizmet Sektörünün Ekonomideki Yeri",
        "Küresel Ticaret",
        "Bölgeler ve Ülkeler",
        "İlk Uygarlıklar",
        "Kültür Bölgeleri ve Türk Kültürü",
        "Sanayileşme Süreci: Almanya",
        "Tarım ve Ekonomi İlişkisi Fransa – Somali",
        "Ülkeler Arası Etkileşim",
        "Jeopolitik Konum",
        "Çatışma Bölgeleri",
        "Küresel ve Bölgesel Örgütler",
        "Çevre ve Toplum",
        "Çevre Sorunları ve Türleri",
        "Madenler ve Enerji Kaynaklarının Çevreye Etkisi",
        "Doğal Kaynakların Sürdürülebilir Kullanımı",
        "Ekolojik Ayak İzi",
        "Doğal Çevrenin Sınırlılığı",
        "Çevre Politikaları",
        "Çevresel Örgütler",
        "Çevre Anlaşmaları",
        "Doğal Afetler"
      ]
    },
    "Felsefe": {
      color: "#607d8b",
      topics: [
        "Felsefenin Tanımı ve Konusu",
        "Felsefenin Temel Kavramları",
        "Felsefenin Alanları (Bilgi, Ahlak, Varlık, Siyaset, Sanat, Din felsefesi)",
        "Felsefenin Temel Problemleri",
        "Bilgi Felsefesi",
        "Varlık Felsefesi",
        "Ahlak Felsefesi",
        "Siyaset Felsefesi",
        "Sanat Felsefesi",
        "Din Felsefesi",
        "Bilim Felsefesi",
        "İlk Çağ Felsefesi",
        "Orta Çağ Felsefesi",
        "Yeni Çağ Felsefesi",
        "Aydınlanma Felsefesi",
        "19 ve 20. Yüzyıl Felsefesi",
        "Türk-İslam Düşünürleri",
        "Anadolu'da Felsefi Düşünce"
      ]
    },
    "Din Kültürü": {
      color: "#00bcd4",
      topics: [
        "Bilgi ve İnanç",
        "Bilginin Kaynakları (Vahiy, Akıl, Duyular)",
        "Akıl ve Bilgi İlişkisi",
        "İslam Medeniyetinde Bilim İnsanları",
        "İslam Düşüncesinde Yorumlar",
        "İtikadi Mezhepler (Maturidilik, Eş'arilik vb.)",
        "Ameli Mezhepler (Hanefilik, Şafiilik vb.)",
        "Tasavvufun Temelleri",
        "Tarikatlar ve Temsilcileri",
        "İslam ve Estetik (Sanat ve Mimari)",
        "Hz. Muhammed'in Hayatından Örnekler",
        "İslam Ahlakı ve Değerler Eğitimi",
        "İslam'da İnsan ve Hayat",
        "Kur'an'da İnsan ve Evren",
        "Kur'an'dan Mesajlar (Seçilen Ayetler ve Tefsiri)",
        "Vahiy ve Akıl İlişkisi",
        "Din ve Laiklik",
        "Dinde Yorum Farklılıkları",
        "İslam ve Diğer Dinler",
        "Güncel Dini Meseleler",
        "Dini ve Ahlaki Gelişim",
        "Hak ve Adalet",
        "Toplum ve Ahlak",
        "İslam'da Çevre ve Doğa Anlayışı",
        "İslam'da Aile ve Toplum"
      ]
    }
  }
};

export default yksData;
